set nocompatible
"set background=dark
"if !has("gui_running")
"   set t_Co=256
"endif
":colorscheme peaksea " pretty colors
set ruler
set mouse=a
set tabstop=4
set sw=4
set softtabstop=4
"set backspace=2
set showmatch
syntax on
set foldmethod=marker
"set number
set encoding=utf-8
set scrolloff=3
set showmode
set showcmd
set hidden
set wildmenu
set wildmode=list:longest
set visualbell
set cursorline
set ttyfast
set backspace=indent,eol,start
set laststatus=2
set relativenumber
set undofile
set nobackup
set noswapfile

let mapleader = ","

nnoremap / /\v
vnoremap / /\v
set ignorecase
set smartcase
set gdefault
set incsearch
set showmatch
set hlsearch
" clear out a search with ,<space>
nnoremap <leader><space> :noh<cr>
" use tab to match bracket pairs
nnoremap <tab> %
vnoremap <tab> %

set wrap
set textwidth=79
set formatoptions=qrn1
set colorcolumn=85

" autosave on lose focus
au FocusLost * :wa

" jj goes to normal mode, hmmm
inoremap jj <ESC>


" creates a new vertical split and switches over to it
nnoremap <leader>w <C-w>v<C-w>l

" Switch between splits easily
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" remaps ,a to :Ack
nnoremap <leader>a :Ack

" auto change to the directory of the current file I'm working on
autocmd BufEnter * lcd %:p:h

runtime perforce/perforcemenu.vim

:colorscheme molokai

:let g:p4CmdPath = '~/bin/p4'


filetype indent on
au BufNewFile,BufRead *.tex set spell cindent shiftwidth=4
" .gra files for 11-721
au BufNewFile,BufRead *.gra set filetype=lisp autoindent
" For flex development
au BufNewFile,BufRead *.as set filetype=actionscript
au BufNewFile,BufRead *.mxml set filetype=mxml

augroup mkd
    autocmd BufRead *.mkd set ai formatoptions=tcroqn2 comments=n:>
augroup END

"insert one character
noremap <C-x> 	i<Space><Esc>r

filetype plugin on
set grepprg=grep\ -nH\

:iab #t /***************************************************************
:iab #b <space>***************************************************************/

map ,* :call CommentLinePincer('/*','*/')<CR>+
map ,/ :call CommentLineToEnd('//')<CR>+

" allow the switching of buffers with C-TAB
let g:miniBufExplMapCTabSwitchBufs = 1

function! Gnome()
   set ts=8
   if !exists("autocommands_loaded")
      let autocommands_loaded = 1
      augroup C
         autocmd BufRead *.c set cindent
      augroup END
   endif
endfunction

map ,g :call Gnome()<CR>+

let g:DoxygenToolkit_authorName="Mike Glazer (mglazer)"
let g:DoxygenToolkit_blockHeader="******************************************************************************"
let g:DoxygenToolkit_blockFooter="******************************************************************************"


" work around for Vim 7.0 and Latex-Suite problems
let g:tex_flavor='latex'

inoremap <C-l> <C-x><C-o>
nmap <C-tab> :tabnext<CR>
nmap <C-S-tab> :tabprevious<CR>
nmap <C-t> :tabnew<CR>

nnoremap <silent> <F6> :TlistToggle<CR>
let Tlist_Ctags_Cmd="/opt/local/bin/ctags"

